apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    name: customer-service
spec:
  replicas: 1
  selector:
      matchLabels:
        name: customer-service
  template:
    metadata:
      labels:
        name: customer-service
    spec:
      containers:
      - name: customer-service
        image: gcr.io/icepegasus/customer-service
        ports:
        - containerPort: 3333
          protocol: TCP